version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: diplom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    # extra_hosts:
    # - "host.docker.internal:host-gateway"

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "yarn add @t3-oss/env-nextjs && yarn db:generate && yarn db:migrate",
      ]

    environment:
      - DATABASE_URL=postgresql://postgres:postgresql@db:5432/diplom
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgresql@db:5432/diplom
      - AUTH_SECRET=1kmQL7B8Ec5k6UCLGXvQSK5f5fwGJlf/icn/9qAeYXI=
      - OAUTH_CLIENT_ID=1094050481038-chejip4sppoo51an12l2vun57hfhm5rr.apps.googleusercontent.com
      - OAUTH_CLIENT_SECRET=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
      - CHECKOUT_PRIVATE_KEY=sk_sbox_5khfurmbfwspd5gti6z2wodicyk
      - CHECKOUT_CHANNEL_ID=pc_jdqqmongbnqeljbi54whdzenmi
      - CHECKOUT_AUTHORIZATION=0de2e922-9d69-4c8d-96d8-281c651361fc
      - CHECKOUT_SIGNATURE_SECRET=d2b2334d-1738-4a41-96f2-0626da613355
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_TRUST_HOST=http://localhost:3000
      - NEXTAUTH_SECRET=marichka_secret
      - HERE_APP_ID=tnlocw9L5CaZ18rKRDbM
      - HERE_API_KEY=DPlThiZyJRk3Pe2S2hKmiRqPi45f6LzrMYu6r8C0uyE
      - SENDGRID_API_KEY=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
      - SENDGRID_DEFAULT_SENDER=igor.com2003@gmail.com
    networks:
      - app-network
    depends_on:
      - db
      - migrations

networks:
  app-network:

volumes:
  postgres_data:
