version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: diplom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    # extra_hosts:
    # - "host.docker.internal:host-gateway"

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "yarn add @t3-oss/env-nextjs && yarn db:generate && yarn db:migrate",
      ]

    environment:
      - DATABASE_URL=postgresql://postgres:postgresql@db:5432/diplom
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - CHECKOUT_PRIVATE_KEY=${CHECKOUT_PRIVATE_KEY}
      - CHECKOUT_CHANNEL_ID=${CHECKOUT_CHANNEL_ID}
      - CHECKOUT_AUTHORIZATION=${CHECKOUT_AUTHORIZATION}
      - CHECKOUT_SIGNATURE_SECRET=${CHECKOUT_SIGNATURE_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - HERE_APP_ID=${HERE_APP_ID}
      - HERE_API_KEY=${HERE_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_DEFAULT_SENDER=${SENDGRID_DEFAULT_SENDER}
    networks:
      - app-network
    depends_on:
      - db
      - migrations

networks:
  app-network:

volumes:
  postgres_data:
