import "~/styles/globals.css";

import { Plus_Jakarta_Sans } from "next/font/google";

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Head from "next/head";
import Script from "next/script";

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${jakartaSans.variable}`}>
      <Head>
        <link
          rel="stylesheet"
          href="https://js.api.here.com/v3/3.1/mapsjs-ui.css"
        />
      </Head>
      <body>
        <Script
          type="text/javascript"
          strategy="beforeInteractive"
          src="https://js.api.here.com/v3/3.1/mapsjs-core.js"
        />
        <Script
          type="text/javascript"
          strategy="beforeInteractive"
          src="https://js.api.here.com/v3/3.1/mapsjs-service.js"
        />
        <Script
          type="text/javascript"
          strategy="beforeInteractive"
          src="https://js.api.here.com/v3/3.1/mapsjs-ui.js"
        />
        <Script
          type="text/javascript"
          strategy="beforeInteractive"
          src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js"
        />
        <div className="min-h-screen overflow-y-auto bg-gray-900 p-8">
          <div className="flex min-h-[calc(100vh-4rem)] w-full flex-1 flex-col items-center justify-center rounded-2xl bg-gray-50">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
